// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

 import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1RJmFg6nMIfXJ8uR5wsIugahCc4-5szI',
    appId: '1:43579719411:web:0c41617777e44faafb0186',
    messagingSenderId: '43579719411',
    projectId: 'recipeapp-e0411',
    authDomain: 'recipeapp-e0411.firebaseapp.com',
    storageBucket: 'recipeapp-e0411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8m-DxNTD0NE4L_qR0--EsnkurjzAc7cY',
    appId: '1:43579719411:android:2a9b11e7326c1c41fb0186',
    messagingSenderId: '43579719411',
    projectId: 'recipeapp-e0411',
    storageBucket: 'recipeapp-e0411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPmQUH1yhSO3M3SnHDcuVlW6gONIprOnw',
    appId: '1:43579719411:ios:7c8ab29c3681b451fb0186',
    messagingSenderId: '43579719411',
    projectId: 'recipeapp-e0411',
    storageBucket: 'recipeapp-e0411.appspot.com',
    iosBundleId: 'com.example.geminiproject',
  );
}

